package: redactor
version: '2.0.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/redactor

vendor_versions:
    redactor: '3.3.5'

conflicts:
    packages:
        redactor2: '<5'

requires:
    redaxo: '^5.9'
    php:
        version: '>=7.3'

page:
    title: 'translate:title'
    perm: admin[]
    pjax: true
    subpages:
        profile:
            title: 'translate:profiles'
        help:
            title: 'translate:help'
            icon: rex-icon fa-info-circle
            itemclass: pull-right
        clear_cache:
            title: 'translate:clear_cache'
            itemclass: 'pull-right'
            href:
                page: redactor/profile
                func: clear_cache
