package: redactor
version: '4.0.0-dev'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/redactor

vendor_versions:
    redactor: '4.0.6'

conflicts:
    packages:
        redactor2: '<5'

requires:
    redaxo: '^5.17'
    php:
        version: '>=8.1'

page:
    title: translate:redactor_title
    icon: rex-icon fa-keyboard
    perm: redactor[]
    subpages:
        profile:
            title: translate:redactor_profiles
            icon: rex-icon fa-keyboard
            perm: redactor[]
        settings:
            title: translate:redactor_settings
            icon: rex-icon fa-gear
            itemclass: pull-right
            perm: admin
        docs:
            title: translate:redactor_docs
            subPath: README.md
            icon: rex-icon fa-info-circle
            itemclass: pull-right
            perm: redactor[docs]
        clear_cache:
            title: 'translate:clear_cache'
            itemclass: 'pull-right'
            linkClass: 'btn btn-delete'
            href:
                page: redactor/profile
                func: clear_cache

editor:
    options:
        # Autoparse
        autoparse: true
        autoparseStart: true
        autoparsePaste: true
        autoparseLinks: true
        autoparseImages: true
        autoparseVideo: true

        # Button
        buttonsTextLabeled: false

        # Clean
        cleanOnEnter: true
        cleanInlineOnEnter: false
        removeScript: true
        removeNewLines: false
        removeComments: true
        replaceTags: {'b': 'strong', 'i': 'em', 'strike': 'del'}

    options_unsupported:
        # Autosave
        autosave: false
        autosaveName: false
        autosaveData: false

        # Button
        buttons: ['html', 'format', 'bold', 'italic', 'deleted', 'lists', 'image', 'file', 'link']
        buttonsAdd: []
        buttonsAddFirst: false # Object Boolean
        buttonsAddAfter: false # Object Boolean
        buttonsAddBefore: false # Object Boolean
        buttonsHide: []
        buttonsHideOnMobile: []
        activeButtons: {b: 'bold', strong: 'bold', i: 'italic', em: 'italic', del: 'deleted', strike: 'deleted'}
        activeButtonsAdd: {}

        # Click-To-Edit
        clickToEdit: false
        clickToSave: false
        clickToCancel: false

        # File
        fileUpload: false
        fileUploadParam: 'file'
        fileData: false
        fileAttachment: false

        # Focus
        focus: false
        focusEnd: false

        # Formatting
        breakline: false
        markup: 'p'
        enterKey: true
        formatting: ['p', 'blockquote', 'pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6']
        formattingAdd: false # Object Boolean
        formattingHide: false # Array Boolean

        # Height and Width
        minHeight: false
        maxHeight: false
        maxWidth: false

        # Image
        imageUpload: false # Boolean String Function
        imageUploadParam: 'file'
        imageData: false # Object Boolean
        imageFigure: false
        imageEditable: true
        imageLink: true
        imageCaption: true
        imagePosition: false # Boolean Object
        imageFloatMargin: '10px'
        imageResizable: false
        imageObserve: true

        # Link
        linkNewTab: false
        linkTarget: false # Boolean String
        linkTitle: false
        linkNofollow: false
        linkSize: 30 # Number
        linkValidation: true

        # Misc
        animation: true
        lang: 'de'
        direction: 'ltr'
        spellcheck: true
        structure: false
        scrollTarget: false
        placeholder: false # Boolean String
        inline: false
        plugins: []
        callbacks: {}
        grammarly: true
        notranslate: false

        # Paste
        pastePlainText: false
        pasteLinkTarget: false # Boolean String
        pasteImages: true
        pasteLinks: true
        pasteClean: true
        pasteKeepStyle: []
        pasteKeepClass: []
        pasteKeepAttrs: ['td', 'th']
        pasteBlockTags: ['pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'table', 'tbody', 'thead', 'tfoot', 'th', 'tr', 'td', 'ul', 'ol', 'li', 'blockquote', 'p', 'figure', 'figcaption']
        pasteInlineTags: ['a', 'img', 'br', 'strong', 'ins', 'code', 'del', 'span', 'samp', 'kbd', 'sup', 'sub', 'mark', 'var', 'cite', 'small', 'b', 'u', 'em', 'i']

        # Pre
        preClass: false # String Boolean
        preSpaces: 4 # Number Boolean

        # Shortcodes
        shortcodes: # Boolean Object
            'p.': { format: 'p' }
            'quote.': { format: 'blockquote' }
            'pre.': { format: 'pre' }
            'h1.': { format: 'h1' }
            'h2.': { format: 'h2' }
            'h3.': { format: 'h3' }
            'h4.': { format: 'h4' }
            'h5.': { format: 'h5' }
            'h6.': { format: 'h6' }
            #'1.': { format: 'ol' }
            '*.': { format: 'ul' }

        # shortcuts
        shortcuts: {} # Boolean Object
        shortcutsAdd: false # Boolean Object

        # Source
        source: true # Boolean Object
        showSource: false

        # Styles
        styles: true
        stylesClass: 'redactor-styles'

        # Tab
        tabindex: false # Boolean Number
        tabAsSpaces: false # Boolean Number
        tabKey: true

        # Toolbar
        air: false
        toolbar: true
        toolbarFixed: true
        toolbarFixedTarget: 'document' # Node String
        toolbarFixedTopOffset: 0 # Number
        toolbarExternal: false
        toolbarContext: true

        # Upload
        dragUpload: true
        multipleUpload: true
        clipboardUpload: true
        uploadData: false


default_config:
#    field: 'Test' # Bei der Installation belegt REDAXO automatisch in der rex_config-Tabelle im Namespace `redactor` im Feld `field` den Wert `Test` 

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
